# Unit 00: Baseline Vectors and Embeddings

Use this notebook to type and run the PyTorch exercises yourself. The prompt cells tell you what to solve; the code cells are intentionally blank.

## Setup

Import PyTorch before starting.

API you may need:

```python
import torch
```

In [2]:
import torch

## Tensor Exploration (~5 min)

The goal is to feel what a tensor is, not to compute anything important. A tensor has a shape and a dtype, you index it like a list, and operations care about shapes matching.

### 1. Create a 1-D tensor

Create a 1-D tensor with the values `[3, -2, 5, 1]` using `torch.tensor(...)`. Print it.

API you may need:

```python
torch.tensor([...])
print(x)
```

In [3]:
x = torch.tensor([3, -2, 5, 1])
print(x)

tensor([ 3, -2,  5,  1])


In [4]:
type(x)

torch.Tensor

In [6]:
x.shape

torch.Size([4])

### 2. Inspect tensor attributes

Inspect three attributes: `.shape`, `.dtype`, `.ndim`. Make sure you can articulate what each tells you. `ndim` should be 1. Why?

API you may need:

```python
x.shape
x.dtype
x.ndim
```

In [7]:
x.dtype

torch.int64

In [8]:
# 1 dimension - it's just a vector, a single ordered list of numbers
# to represent a direction in some space, a point from the origin
x.ndim

1

### 3. Compare int vs float

Create the same tensor twice: once with no decimal points (`[3, -2, 5, 1]`) and once with them (`[3., -2., 5., 1.]`). Compare `.dtype`. Why does float matter for ML?

API you may need:

```python
torch.tensor([3, -2, 5, 1])
torch.tensor([3., -2., 5., 1.])
x.dtype
```

In [9]:
integer = torch.tensor([3, -2, 5, 1])
floats = torch.tensor([3., -2., 5., 1])

In [10]:
integer.dtype

torch.int64

In [11]:
floats.dtype

torch.float32

### 4. Index it

Get the first element. Get the last element using a negative index. Try `.item()` on a single element. What does it return, and how is it different from the element itself?

API you may need:

```python
x[0]
x[-1]
x[0].item()
```

In [15]:
x

tensor([ 3, -2,  5,  1])

In [13]:
x[0]

tensor(3)

In [16]:
x[0].item()

3

In [14]:
x[-1]

tensor(1)

### 5. Try to break it

Add a tensor of shape `(3,)` to a tensor of shape `(4,)`. Read the error carefully. This is the most common shape bug you'll hit later.

API you may need:

```python
torch.tensor([...])
a + b
a.shape
b.shape
```

In [17]:
a = torch.tensor([-1.2, 3.5, 5.])
b = torch.tensor([3, 8.0, 1.3, -5.5])
a + b

RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 0

In [19]:
b = torch.tensor([3, 8.0, 1.3])
a+b

tensor([ 1.8000, 11.5000,  6.3000])

### 6. Discover two constructors

Make a tensor of 10 zeros. Then make a tensor of 10 random numbers from a normal distribution. Print their shapes.

API you may need:

```python
torch.zeros(10)
torch.randn(10)
x.shape
```

In [22]:
z = torch.zeros(10)
r = torch.randn(10)
print(z)
print(r)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
tensor([-1.3434,  0.7003, -0.5409,  0.8248, -0.7156,  1.5569, -0.6257,  0.5871,
         1.1022, -1.5476])


In [24]:
z.shape

torch.Size([10])

## PyTorch Problems

Re-solve the 7 by-hand problems in PyTorch. Use the same vectors and same operations from the unit note. The point is to verify your paper math and feel that the syntax matches the notation: `+` is addition, `*` is scalar multiplication.

### Problems 1-7. Re-solve the by-hand vector problems

For each by-hand problem from the unit note, create the needed tensors and compute the result in PyTorch. Compare the notebook output to your paper result.

1. u = (3, -2)                            compute 4u
2. a = (1, 5),         b = (-2, 3)        compute a + b
3. p = (2, 0, -1)                         compute -3p
4. v = (1, 2, 3),      w = (4, -1, 0)     compute v + w
5. x = (2, -1),        y = (3, 4)         compute 2x + 3y
6. a = (1, -1, 2),     b = (0, 3, -1)     compute 5a + 2b
7. p = (1, 0, -2, 4),  q = (3, -1, 2, 0)  compute 2p + q

API you may need:

```python
torch.tensor([...])
a + b
a - b
scalar * a
a.shape
```

In [26]:
u = torch.tensor([3, -2])
4 * u

tensor([12, -8])

In [27]:
a = torch.tensor([1, 5])
b = torch.tensor([-2, 3])
a + b

tensor([-1,  8])

In [29]:
p = torch.tensor([2, 0, -1])
-3 * p

tensor([-6,  0,  3])

In [30]:
v = torch.tensor([1, 2, 3])
w = torch.tensor([4, -1, 0])
v + w

tensor([5, 1, 3])

In [31]:
x = torch.tensor([2, -1])
y = torch.tensor([3, 4])
(2 * x) + (3 * y)

tensor([13, 10])

In [32]:
a = torch.tensor([1, -1, 2])
b = torch.tensor([0, 3, -1])
(5 * a) + (2 * b)

tensor([5, 1, 8])

In [33]:
p = torch.tensor([1, 0, -2, 4])
q = torch.tensor([3, -1, 2, 0])
(2 * p) + q

tensor([ 5, -1, -2,  8])

### 8. Scale up

Create two random 1-D tensors of size 1000. Compute `3a + 2b`. Same operations, 1000 components, same syntax. Confirm the result has shape `(1000,)`.

API you may need:

```python
torch.randn(1000)
3 * a + 2 * b
result.shape
```

In [34]:
a = torch.randn(1000)
b = torch.randn(1000)

In [36]:
result = (3 * a) + (2 * b)
print(result[0:10])

tensor([-2.7882, -0.7763,  3.3200,  0.2137, -1.5600,  6.4619, -8.3961, -0.7429,
         4.8276, -2.1462])


In [37]:
result.shape

torch.Size([1000])

### 9. Standard basis check

Create the vector `e2 = (0, 1, 0, 0)` in R^4 as a tensor. Compute `3 * e2`. Visually confirm scalar multiplication only changes the nonzero coordinate. Then add `e2` to `e3 = (0, 0, 1, 0)`. What shape does the result have, and what's special about it geometrically?

API you may need:

```python
torch.tensor([...])
3 * e2
e2 + e3
result.shape
```

In [38]:
e2 = torch.tensor([0, 1, 0, 0])
print(3 * e2)

tensor([0, 3, 0, 0])


In [40]:
e3 = torch.tensor([0, 0, 1, 0])
e2 + e3

tensor([0, 1, 1, 0])

## Finish
